/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicus.common.service.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.medicus.common.service.model.Interview_Request;
import com.medicus.common.service.service.Interview_RequestLocalServiceUtil;

/**
 * The extended model base implementation for the Interview_Request service. Represents a row in the &quot;Medicus_Interview_Request&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link Interview_RequestImpl}.
 * </p>
 *
 * @author sandip.patel
 * @see Interview_RequestImpl
 * @see Interview_Request
 * @generated
 */
@ProviderType
public abstract class Interview_RequestBaseImpl
	extends Interview_RequestModelImpl implements Interview_Request {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a interview_ request model instance should use the {@link Interview_Request} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			Interview_RequestLocalServiceUtil.addInterview_Request(this);
		}
		else {
			Interview_RequestLocalServiceUtil.updateInterview_Request(this);
		}
	}
}