/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicus.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Address service. Represents a row in the &quot;Medicus_Address&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.medicus.common.service.model.impl.AddressModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.medicus.common.service.model.impl.AddressImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Address
 * @see com.medicus.common.service.model.impl.AddressImpl
 * @see com.medicus.common.service.model.impl.AddressModelImpl
 * @generated
 */
@ProviderType
public interface AddressModel extends BaseModel<Address> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a address model instance should use the {@link Address} interface instead.
	 */

	/**
	 * Returns the primary key of this address.
	 *
	 * @return the primary key of this address
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this address.
	 *
	 * @param primaryKey the primary key of this address
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the address ID of this address.
	 *
	 * @return the address ID of this address
	 */
	public long getAddressId();

	/**
	 * Sets the address ID of this address.
	 *
	 * @param addressId the address ID of this address
	 */
	public void setAddressId(long addressId);

	/**
	 * Returns the user ID of this address.
	 *
	 * @return the user ID of this address
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this address.
	 *
	 * @param userId the user ID of this address
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this address.
	 *
	 * @return the user uuid of this address
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this address.
	 *
	 * @param userUuid the user uuid of this address
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the address1 of this address.
	 *
	 * @return the address1 of this address
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this address.
	 *
	 * @param address1 the address1 of this address
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the address2 of this address.
	 *
	 * @return the address2 of this address
	 */
	@AutoEscape
	public String getAddress2();

	/**
	 * Sets the address2 of this address.
	 *
	 * @param address2 the address2 of this address
	 */
	public void setAddress2(String address2);

	/**
	 * Returns the city of this address.
	 *
	 * @return the city of this address
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this address.
	 *
	 * @param city the city of this address
	 */
	public void setCity(String city);

	/**
	 * Returns the zipcode of this address.
	 *
	 * @return the zipcode of this address
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this address.
	 *
	 * @param zipcode the zipcode of this address
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the state of this address.
	 *
	 * @return the state of this address
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this address.
	 *
	 * @param state the state of this address
	 */
	public void setState(String state);

	/**
	 * Returns the country of this address.
	 *
	 * @return the country of this address
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this address.
	 *
	 * @param country the country of this address
	 */
	public void setCountry(String country);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Address address);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Address> toCacheModel();

	@Override
	public Address toEscapedModel();

	@Override
	public Address toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}