/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicus.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the School service. Represents a row in the &quot;Medicus_School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.medicus.common.service.model.impl.SchoolModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.medicus.common.service.model.impl.SchoolImpl}.
 * </p>
 *
 * @author sandip.patel
 * @see School
 * @see com.medicus.common.service.model.impl.SchoolImpl
 * @see com.medicus.common.service.model.impl.SchoolModelImpl
 * @generated
 */
@ProviderType
public interface SchoolModel extends BaseModel<School> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a school model instance should use the {@link School} interface instead.
	 */

	/**
	 * Returns the primary key of this school.
	 *
	 * @return the primary key of this school
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this school.
	 *
	 * @param primaryKey the primary key of this school
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the school ID of this school.
	 *
	 * @return the school ID of this school
	 */
	public long getSchoolId();

	/**
	 * Sets the school ID of this school.
	 *
	 * @param schoolId the school ID of this school
	 */
	public void setSchoolId(long schoolId);

	/**
	 * Returns the name of this school.
	 *
	 * @return the name of this school
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this school.
	 *
	 * @param name the name of this school
	 */
	public void setName(String name);

	/**
	 * Returns the address1 of this school.
	 *
	 * @return the address1 of this school
	 */
	@AutoEscape
	public String getAddress1();

	/**
	 * Sets the address1 of this school.
	 *
	 * @param address1 the address1 of this school
	 */
	public void setAddress1(String address1);

	/**
	 * Returns the city of this school.
	 *
	 * @return the city of this school
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this school.
	 *
	 * @param city the city of this school
	 */
	public void setCity(String city);

	/**
	 * Returns the state of this school.
	 *
	 * @return the state of this school
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this school.
	 *
	 * @param state the state of this school
	 */
	public void setState(String state);

	/**
	 * Returns the country of this school.
	 *
	 * @return the country of this school
	 */
	@AutoEscape
	public String getCountry();

	/**
	 * Sets the country of this school.
	 *
	 * @param country the country of this school
	 */
	public void setCountry(String country);

	/**
	 * Returns the zipcode of this school.
	 *
	 * @return the zipcode of this school
	 */
	@AutoEscape
	public String getZipcode();

	/**
	 * Sets the zipcode of this school.
	 *
	 * @param zipcode the zipcode of this school
	 */
	public void setZipcode(String zipcode);

	/**
	 * Returns the contact number of this school.
	 *
	 * @return the contact number of this school
	 */
	@AutoEscape
	public String getContactNumber();

	/**
	 * Sets the contact number of this school.
	 *
	 * @param contactNumber the contact number of this school
	 */
	public void setContactNumber(String contactNumber);

	/**
	 * Returns the website link of this school.
	 *
	 * @return the website link of this school
	 */
	@AutoEscape
	public String getWebsiteLink();

	/**
	 * Sets the website link of this school.
	 *
	 * @param websiteLink the website link of this school
	 */
	public void setWebsiteLink(String websiteLink);

	/**
	 * Returns the contact person name of this school.
	 *
	 * @return the contact person name of this school
	 */
	@AutoEscape
	public String getContactPersonName();

	/**
	 * Sets the contact person name of this school.
	 *
	 * @param contactPersonName the contact person name of this school
	 */
	public void setContactPersonName(String contactPersonName);

	/**
	 * Returns the contact person phone number of this school.
	 *
	 * @return the contact person phone number of this school
	 */
	@AutoEscape
	public String getContactPersonPhoneNumber();

	/**
	 * Sets the contact person phone number of this school.
	 *
	 * @param contactPersonPhoneNumber the contact person phone number of this school
	 */
	public void setContactPersonPhoneNumber(String contactPersonPhoneNumber);

	/**
	 * Returns the contact person email of this school.
	 *
	 * @return the contact person email of this school
	 */
	@AutoEscape
	public String getContactPersonEmail();

	/**
	 * Sets the contact person email of this school.
	 *
	 * @param contactPersonEmail the contact person email of this school
	 */
	public void setContactPersonEmail(String contactPersonEmail);

	/**
	 * Returns the status of this school.
	 *
	 * @return the status of this school
	 */
	public int getStatus();

	/**
	 * Sets the status of this school.
	 *
	 * @param status the status of this school
	 */
	public void setStatus(int status);

	/**
	 * Returns the create date of this school.
	 *
	 * @return the create date of this school
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this school.
	 *
	 * @param createDate the create date of this school
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this school.
	 *
	 * @return the created by of this school
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this school.
	 *
	 * @param createdBy the created by of this school
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this school.
	 *
	 * @return the modified date of this school
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this school.
	 *
	 * @param modifiedDate the modified date of this school
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this school.
	 *
	 * @return the modified by of this school
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this school.
	 *
	 * @param modifiedBy the modified by of this school
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(School school);

	@Override
	public int hashCode();

	@Override
	public CacheModel<School> toCacheModel();

	@Override
	public School toEscapedModel();

	@Override
	public School toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}