/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.medicus.common.service.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Student_Externship service. Represents a row in the &quot;Medicus_Student_Externship&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.medicus.common.service.model.impl.Student_ExternshipModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.medicus.common.service.model.impl.Student_ExternshipImpl}.
 * </p>
 *
 * @author sandip.patel
 * @see Student_Externship
 * @see com.medicus.common.service.model.impl.Student_ExternshipImpl
 * @see com.medicus.common.service.model.impl.Student_ExternshipModelImpl
 * @generated
 */
@ProviderType
public interface Student_ExternshipModel extends BaseModel<Student_Externship> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a student_ externship model instance should use the {@link Student_Externship} interface instead.
	 */

	/**
	 * Returns the primary key of this student_ externship.
	 *
	 * @return the primary key of this student_ externship
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this student_ externship.
	 *
	 * @param primaryKey the primary key of this student_ externship
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the student externship ID of this student_ externship.
	 *
	 * @return the student externship ID of this student_ externship
	 */
	public long getStudentExternshipId();

	/**
	 * Sets the student externship ID of this student_ externship.
	 *
	 * @param studentExternshipId the student externship ID of this student_ externship
	 */
	public void setStudentExternshipId(long studentExternshipId);

	/**
	 * Returns the student ID of this student_ externship.
	 *
	 * @return the student ID of this student_ externship
	 */
	public long getStudentId();

	/**
	 * Sets the student ID of this student_ externship.
	 *
	 * @param studentId the student ID of this student_ externship
	 */
	public void setStudentId(long studentId);

	/**
	 * Returns the partner ID of this student_ externship.
	 *
	 * @return the partner ID of this student_ externship
	 */
	public long getPartnerId();

	/**
	 * Sets the partner ID of this student_ externship.
	 *
	 * @param partnerId the partner ID of this student_ externship
	 */
	public void setPartnerId(long partnerId);

	/**
	 * Returns the employer ID of this student_ externship.
	 *
	 * @return the employer ID of this student_ externship
	 */
	public long getEmployerId();

	/**
	 * Sets the employer ID of this student_ externship.
	 *
	 * @param employerId the employer ID of this student_ externship
	 */
	public void setEmployerId(long employerId);

	/**
	 * Returns the start date of this student_ externship.
	 *
	 * @return the start date of this student_ externship
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this student_ externship.
	 *
	 * @param startDate the start date of this student_ externship
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this student_ externship.
	 *
	 * @return the end date of this student_ externship
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this student_ externship.
	 *
	 * @param endDate the end date of this student_ externship
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the no of hours per week of this student_ externship.
	 *
	 * @return the no of hours per week of this student_ externship
	 */
	public int getNoOfHoursPerWeek();

	/**
	 * Sets the no of hours per week of this student_ externship.
	 *
	 * @param noOfHoursPerWeek the no of hours per week of this student_ externship
	 */
	public void setNoOfHoursPerWeek(int noOfHoursPerWeek);

	/**
	 * Returns the status of this student_ externship.
	 *
	 * @return the status of this student_ externship
	 */
	public int getStatus();

	/**
	 * Sets the status of this student_ externship.
	 *
	 * @param status the status of this student_ externship
	 */
	public void setStatus(int status);

	/**
	 * Returns the mid point review of this student_ externship.
	 *
	 * @return the mid point review of this student_ externship
	 */
	public Date getMidPointReview();

	/**
	 * Sets the mid point review of this student_ externship.
	 *
	 * @param midPointReview the mid point review of this student_ externship
	 */
	public void setMidPointReview(Date midPointReview);

	/**
	 * Returns the mid point review comment of this student_ externship.
	 *
	 * @return the mid point review comment of this student_ externship
	 */
	@AutoEscape
	public String getMidPointReviewComment();

	/**
	 * Sets the mid point review comment of this student_ externship.
	 *
	 * @param midPointReviewComment the mid point review comment of this student_ externship
	 */
	public void setMidPointReviewComment(String midPointReviewComment);

	/**
	 * Returns the final review of this student_ externship.
	 *
	 * @return the final review of this student_ externship
	 */
	public Date getFinalReview();

	/**
	 * Sets the final review of this student_ externship.
	 *
	 * @param finalReview the final review of this student_ externship
	 */
	public void setFinalReview(Date finalReview);

	/**
	 * Returns the final review comment of this student_ externship.
	 *
	 * @return the final review comment of this student_ externship
	 */
	@AutoEscape
	public String getFinalReviewComment();

	/**
	 * Sets the final review comment of this student_ externship.
	 *
	 * @param finalReviewComment the final review comment of this student_ externship
	 */
	public void setFinalReviewComment(String finalReviewComment);

	/**
	 * Returns the create date of this student_ externship.
	 *
	 * @return the create date of this student_ externship
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this student_ externship.
	 *
	 * @param createDate the create date of this student_ externship
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this student_ externship.
	 *
	 * @return the created by of this student_ externship
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this student_ externship.
	 *
	 * @param createdBy the created by of this student_ externship
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this student_ externship.
	 *
	 * @return the modified date of this student_ externship
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this student_ externship.
	 *
	 * @param modifiedDate the modified date of this student_ externship
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this student_ externship.
	 *
	 * @return the modified by of this student_ externship
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this student_ externship.
	 *
	 * @param modifiedBy the modified by of this student_ externship
	 */
	public void setModifiedBy(long modifiedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Student_Externship student_Externship);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Student_Externship> toCacheModel();

	@Override
	public Student_Externship toEscapedModel();

	@Override
	public Student_Externship toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}